"""Dodaj bio do User i description do Article

Revision ID: 7e4b5d569170
Revises: 7cc72aae6e58
Create Date: 2026-01-17 21:23:32.261405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4b5d569170'
down_revision = '7cc72aae6e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
